name: Docker image CI/CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3

      - name: Build docker image
      - uses: docker build -t tadakbe:latest

      - name: Docker login & push
      - uses: docker login -u ghcr.io -u ${{ secretes.GHCR_USERNAME }} -p ${{ secrets.GHCR_PASSWORD }}
      - uses: docker push ghcr.io/kweonminsung/tadakbe:latest

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login -u ghcr.io -u ${{ secretes.GHCR_USERNAME }} -p ${{ secrets.GHCR_PASSWORD }}
            docker-compose pull
            docker-compose up --force-recreate --build -d
